data:
  raw_data_path:     "data/raw/btc_ohlcv_5min_raw.csv"
  feature_data_path: "data/processed/btc_ohlcv_5min_engineered.csv"
  backtrader_data_path: "data/features_with_exp_returns.csv"
  exp_return_parquet_path: data/features_with_exp_returns.parquet
  start_date: "2024-12-01"
  end_date:   "2025-08-25"

exchange:
  name: binance
  symbol: BTCUSDT  
  symbol2:         "BTC/USD:BTC"    
  interval_minute: 5
  timeout:    30
  retries:    3       # how many times to retry on transient failures
  retry_backoff: 5    # seconds between retry attempts
  api_key:    "d54pnJd9e84rSo+/mrh74vSriju7L6phIlNq5SWyNjVLUrSrfFI+4vuM"
  api_secret: "+XYZr9fZWuI/tqWYr69768JjAUGrgI+RX1YR95Dckml/jItosuneE02pfbzAM9Fy5q8Kuzesf2f3c1NvXCNSkw=="


features:
  indicators:
    - sma: {window: 20}
    - rsi: {window: 14}
  drop_na: true

model:
  horizons: [1,12,24,48]
  type: "xgboost"
  features: "models/final_xgb_model_features.json"
  hyperparameters:
    n_estimators: 100
    max_depth:    5
    learning_rate: 0.1
  output_dir: "models"
  filename:   "final_xgb_model.json"

tuning:
  method: "grid"
  param_grid:
    max_depth:       [3,5,7]
    learning_rate:   [0.01,0.1]
  cv:              5
  scoring:         null
  n_iter:          10
  random_state:    42
  n_jobs:          -1
  verbose:         0
  results_dir:     "results"
  results_filename: "tuning_results.json"

training:
  fit_params:     {}
  epochs:         50
  batch_size:     32
  validation_split: 0.2
  start_date: "2025-06-01"
  end_date:   "2025-08-01"

selection:
  method: "shap"
  top_k:    10


backtest:
  start_date: "2025-08-01"
  end_date:   "2025-08-24"
  cash:       10000
  commission: 0.0025
  slippage_perc: 0.0002
  max_bars: 3000
  quiet: true

trading_logic:
  model_paths:
    "1":  "models/xgb_h1.json"
    "12": "models/xgb_h12.json"
    "24": "models/xgb_h24.json"
    "48": "models/xgb_h48.json"
  max_hold_bars: 75
  horizon_weights: [0.29, 0.56, 0.13, 0.01]
  fee_rate:       0.0001
  vol_window:     30
  max_position:   1
  min_trade_size: 0.01
  cooldown_bars: 3.0
  min_edge_bps: 10.0
  persistence: 2
  threshold_mult: 0.09
  z_threshold: 0.3
  sigma_floor_bps: 2.5
  stop_loss_atr_mult: 4
  take_profit_atr_mult: 8
  tick_size: 0.001
  quantile_window: 400  # shorter lookback
  entry_quantile: 0.85   


calibration:
  enabled: true        
  auto_fit: false       # if missing/stale, fit before backtest
  val_frac: 0.2        # last 20% of train window used for calibration
  clip_mode: quantile  # winsorize realized bps during fit
  clip_q: 0.99         # 99th percentile cap
  min_samples: 800     # skip fit if too few points
  suffix: "_calib.joblib"  # file saved next to each model
  quiet: false


logging:
  level: INFO
  format: '%(asctime)s [%(name)s] %(levelname)s: %(message)s'
  handlers:
    console:
      enabled: true
    file:
      enabled: true
      filename: 'logs/app.log'



