data:
  raw_data_path:     "data/raw/btc_ohlcv_5min_raw.csv"
  feature_data_path: "data/processed
  cleaned_data_path:   "data/processed/btc_ohlcv_5min_cleaned.csv"


exchange:
  name: kraken
  symbol: XBTUSD
  interval_minute: 5
  api_key: "${KRAKEN_API_KEY}"
  secret: "${KRAKEN_SECRET}"
  timeout: 30

backtest:
  start_date: "2021-01-01"
  end_date:   "2021-12-31"
  cash:       10000
  commission: 0.0025

features:
  indicators:
    - sma: {window: 20}
    - rsi: {window: 14}
  drop_na: true

model:
  type: "xgboost"
  hyperparameters:
    n_estimators: 100
    max_depth:    5
    learning_rate: 0.1
  output_dir: "models"
  filename:   "final_xgb_model.json"

tuning:
  method: "grid"
  param_grid:
    max_depth:       [3,5,7]
    learning_rate:   [0.01,0.1]
  cv:              5
  scoring:         null
  n_iter:          10
  random_state:    42
  n_jobs:          -1
  verbose:         0
  results_dir:     "results"
  results_filename: "tuning_results.json"

training:
  fit_params:     {}
  epochs:         50
  batch_size:     32
  validation_split: 0.2

selection:
  method: "shap"
  top_k:    10
